server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: be-customer-kyc-api
  datasource:
    url: jdbc:postgresql://${KYC_DB_HOST:localhost}:${KYC_DB_PORT:5432}/${KYC_DB_NAME:customer_kyc_db}
    username: ${KYC_DB_USERNAME:customer_kyc}
    password: ${KYC_DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/digital-wallet}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/digital-wallet/protocol/openid-connect/certs}

wallet:
  kyc:
    auth-api-base-url: ${AUTH_API_BASE_URL:http://localhost:8081}
    security:
      document-hmac-secret: ${KYC_DOCUMENT_HMAC_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
